jaywcjlove/reference

docs/http-status-code.md

==> 请求的页面已移至新的 url  & 请求的页面已临时移动到新的 url

docs(http-status-code): md '_' conversion error

---

docs/golang.md

change golang -> go in WaitGroup code block

doc: fix code highlight

---

package.json

chore: solve the use of pnpm not part of the package

---

.lintstagedrc
.markdownlint.json
package.json

fix markdown file automatically

---

docs/rust.md

content: add some content in the rust

---

docs/ffmpeg.md

content: add fliter in the ffmpeg

---

docs/javascript.md

decodeURI(enc); encodeURI(uri); 注释修正

Update javascript.md（decodeURI(enc); encodeURI(uri); 注释修正 ）

---

docs/vue.md

说明：组合式API是Vue3的最大特点和更改，并且是官方强烈推荐的，虽然选项式API可以使用，但这个并不能代表Vue3的备忘清单

feat: 将vue3中的代码由选项式API转成组合式API，并添加vue3的组合式API响应式基础

---

docs/bash.md

Update bash.md for a translation error

---

docs/python.md

optimize some translation in  python :)

fix: optimize translation in python doc

---

docs/cmake.md

change docs/cmake.md

---

docs/c.md

fix typo: 单个字符并非字符串

---

docs/jq.md

docs(jq): 字符串转数组

---

docs/dockerfile.md

- 修改意图
- 原文档这个部分，只写了服务静态网站的最小 Docker 镜像，更多信息全在引用的英文文档部分，信息量不多，所以考虑替换原部分
- 运行展示

docs(dockerfile):添加用于减小镜像体积的多阶段构建

---

docs/ansible.md

docs(ansible): 格式化“另见”

---

docs/vue2.md

v-for和v-if不推荐一起使用,效率较低.推荐使用computed计算属性.
当两者一起使用时v-for具有较高的优先级.

v-for和v-if不推荐一起使用

---

README.md
docs/apt.md

个人觉得包管理工具在平时使用中的频率还是比较高的，所以就想着把一些常用的apt命令进行总结，为大家提供一定的便利性。

docs:在命令板块新增了APT命令

---

docs/vue.md

docs: wath--->watch

---

docs/latex.md

[docs:latex]完善一些常用的数学符号，添加一些大小可变的符号，添加一些使用描述，添加PDF引用链接

---

docs/dart.md

docs: update dart.md

---

docs/find.md

增加查找并排除的示例

---

README.md
docs/homebrew.md

doc: update homebrew.md

---

docs/cs.md

我怀疑最后的“一般 .NET 条款" 是机翻得来的，修改了一下并且加上了几个概念的中文名称。

doc: maybe better translate of cs.md

---

docs/git.md

docs(git): 添加约定式提交到git.md

---

docs/nginx.md

fix(nginx): fix typo

---

CONTRIBUTING.md
README.md
docs/flutter.md

doc： update flutter.md

---

docs/flutter.md

* 添加Flex、Expanded、Flexible、Spacer组件

doc: update flutter.md

---

docs/webstorm.md

fix: typo txt

---

README.md

add mirror

---

README.md
docs/make.md

docs: add make

---

README.md

@jaywcjlove  我换域名了，麻烦重新推送一下 #102

change domain

---

README.md

add mirror ref.eryajf.net

---

README.md

发现一个镜像站更改了，故而去掉
https://www.ccommunity.cas-air.cn/index.html#/login/name

去掉一个错误的镜像站

---

docs/docker.md
docs/dockerfile.md

doc: update docker.md, dockerfile.md

---

docs/java.md

LocalDate LocalTime LocalDateTime

新增 Java8 时间和日期工具类库

---

README.md

 doc: update README.md.

---

README.md

feat: add mirror

---

docs/javascript.md

新增 javascript 的 Proxy 和 Reflect

feat: add javascript Proxy and Reflect

---

README.md

Add mirror site: reference.kyoma.top 
https://github.com/jaywcjlove/reference/issues/102

Add mirror site

---

README.md

Update new mirrors source: [quickref.caitou.org](https://quickref.caitou.org/)

Update new mirrors source

---

README.md

add a new mirror

---

docs/golang.md
docs/jquery.md

doc: update golang.md

---

docs/python.md

Maybe it's not perfect, but it's better than before

Adjust some translation problems

---

CONTRIBUTING.md
README.md
docs/adb.md
docs/homebrew.md

修正了一些用法和语病(?)
修正了一些错误的东西
还删除了个重复的镜像源

Update adb.md and homebrew.md and delete repeated mirror items

---

docs/bash.md

add bash debug info

---

docs/java.md

doc: update java.md

---

docs/kotlin.md

新增Kotlin的高阶函数用法

---

docs/flask.md

Update flask.md fix spelling mistake

---

README.md
docs/pacman.md

feat: add docs/pacman.md

---

README.md
docs/golang.md

update: update docs/golang.md

---

README.md

docs: 新增镜像站 https://tools.dadatom.com/reference

docs: 新增镜像站 https://tools.dadatom.com/reference

---

README.md

修改镜像站地址，讲 /reference path 修改为 /reference/

docs: 修改镜像站地址

---

docs/ini.md

doc: update docs/ini.md

---

docs/cs.md

feat: `while` and `do...while`

doc: Update cs.md

---

README.md

我这边提供一个镜像站点

---

docs/python.md

添加了使用remove方法移除list内容以及搜索list的方法

添加了使用remove方法移除list内容以及搜索list的方法

---

docs/git.md

`git checkout -b new_branch` 创建新分支后，切换到了该分支。更改后表达的意思更具体了。望采纳。

更正git清单的描述

---

docs/http-status-code.md

Updated some translation from original Chinese docs, include:
- String "Means"
- The translation of 2xx response code
- The translation of 4xx response code
- More specifical explanation of 402 Payment Required response code (original English docs' are too brief) PS: I'm not English native speaker, so there's may grammar mistakes in this PR description.

http-status-code.md translation updated.

---

docs/fastapi.md

默认的3栏布局会导致阅读顺序错误，长代码会被折叠
奉天意，顺民心，FastAPI 备忘清单全部采用1栏布局

doc: update docs/fastapi.md

---

docs/git.md

Git备忘清单 => Git 技巧 => Fork仓库同步上游仓库

doc: update docs/git.md

---

docs/postgres.md

Add a sample documentation for `pg_upgrade`

add doc for pg_upgrade

---

README.md

add ref.wdft.com mirror

---

docs/cs.md

添加了字符串判空操作

---

docs/ansible.md

doc: update ansible.md

---

docs/pytorch.md

Add common pytorch functions squeeze, unsqueeze

add squeeze & unsqueeze for pytorch

---

docs/swift.md

Fix enum and add extension

---

docs/emacs.md

Fix commands in emacs doc

---

docs/iso-3166-1.md

#579 Add content related to simplified and traditional Chinese

doc: Add content related to simplified and traditional Chinese

---

docs/cs.md

新增了c#中的类部分模块，元组模块，集合模块

---

docs/java.md

docs: update docs/java.md.

---

docs/github-actions.md

添加Actions定时执行的配置说明

---

docs/tauri.md

add android in tauri

---

docs/fastapi.md

本次PR提交了：
1、安全性-基于Token的认证
2、安全性-HTTPS 和证书

新增FastAPI中安全性章节的内容

---

docs/pytorch.md

upload some snippets about pytorch cuda accelerating.

doc(pytorch): add cuda related section

---

README.md

Feat: 增加国内镜像网站

---

docs/pinia.md

Create a Pinia Memo List to document common commands and actions of the Pinia State Management Library in markdown format. Content includes getting started, creating Pinia instances, defining the Store, using the Store, and more
support https://github.com/jaywcjlove/reference/issues/495

feats (docs): add Pinia Memo List

---

docs/rxjs.md

Create a new cheat sheet for RxJS covering key concepts, operators, and methods. This includes installation, importing, creating Observables, and using various operators such as map, filter, switchMap, and more. The document also explains important concepts like Schedulers and provides examples for better understanding.

doc: add rxjs.md cheat sheet

---

docs/dart.md

doc: update dart.md

---

docs/nginx.md

doc: update docs/nginx.md

---

docs/docker.md
docs/linux-command.md
docs/nginx.md

添加linux和docker命令

---

docs/postgres.md

-----
<a href="https://stackblitz.com/~/github.com/rainbowatcher/reference/tree/rainbowatcher/patch-78631"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/rainbowatcher/reference/tree/rainbowatcher/patch-78631)._

fix: typo in postgres

---

docs/swift.md
docs/swiftui.md

1、修改Swift 卡片名词，与前一个【变量声明】一致性
2、删除Swift UI中多余的字符
3、修改Swift UI的Layout部分，使其VStack、HStack、ZStack排布整齐
4、增加Swift UI的Lazy懒加载相关内容

Modify Swift && SwiftUI

---

README.md
docs/ports.md

feat: #854 添加端口对照表

---

docs/python.md

pvenv -> pyenv
添加了关于 pyenv 查看版本相关用例

doc: fix pyenv typo and some usecase

---

docs/cs.md

添加了Csharp的事件与委托部分参考

---

docs/latex.md

See the title of each commit for further details

docs: optimize `latex.md`

---

docs/mysql.md

在 MySQL 文档中新增错误处理常用语句 并且在聚合函数中添加了GROUP_CONCAT() 函数 #940

在 MySQL 文档中新增错误处理常用语句和聚合函数中的 GROUP_CONCAT()

---

docs/matlab.md

添加了MATLAB面向对象编程的部分内容。
主要参考《MATLAB面向对象编程——从入门到设计模式》（徐潇，李远），
我的整理笔记：[MATLAB 面向对象学习笔记——1. 基础](https://fenglielie.top/p/5f84fead/)

docs: update MATLAB.md

---

docs/htmx.md

添加来源：
参考资料
---
- [HTMX 官方文档](https://htmx.org/docs/) _(htmx.org)_

docs: 修改HTMX文档的一些过时内容

---

docs/java.md

docs: update java.md content

---

docs/tauri.md

doc: add tauri mobile dev document
