- docs/http-status-code.md
> doc: Correct the anchor(http-status-code)

- docs/markdown.md
Not `<kdb>`, should be `<kbd>`
Reference: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/kbd
> fix: fix typo content in markdown.md

- docs/latex.md
> docs(latex): 为 LaTex 条目添加希腊和希伯来字母

- scripts/nodes/footer.mjs
用 Github Action build 的页脚时间是UTC时区，容易造成误解
先把时间都转UTC，再转CST 中国标准时间
情况一、在国内 build，`now.getTimezoneOffset()` 为 -480，
情况二、在 Github Action build, `now.getTimezoneOffset()` 为 0
都可以得到正确的时间
copilot 真好用 :smile:
> fix: footer timezone bug

- .npmrc
pnpm 对于 refs-cli 中的部分依赖无法提升到根模块，需要使用 shamefully-hoist
> bug: the dependencies of pnpm

- docs/cpp.md
1. 更新排版：更新了以下内容的排版，以适应网页的风格：
+ lambda表达式
+ 多线程
2. 更新互斥锁部分：
+ `mutex`
+ 上锁——`lock`
+ 解锁——`unlock`
+ 尝试上锁——`try_lock`
+ `lock_guard<Mutex>`
+ 额外参数`std::adopt_lock`
+ `unique_lock<Mutex>`
+ 额外参数
+ `std::adopt_lock`
+ `std::try_to_lock`
+ `std::defer_lock`
+ 成员函数
+ `lock`
+ `unlock`
+ `release`
+ `owns_lock`
+ `call_once`
3. 更新条件变量部分：
+ `condition_variable` 
+ `wait`
+ `notify_one`
+ `notify_all`
4. 更新同步、异步及线程运行结果获取部分：
+ `async`
+ `std::launch::deferred`
+ `std::launch::async`
+ `std::deferred | std::launch::async`
+ `future`
+ `wait`
+ `get`
+ `wait_for`
+ `wait_until`
+ `future_status`
+ `ready`
+ `timeout`
+ `deferred`
+ `shared_future`
> 更新C++11多线程内容

- docs/kubernetes.md
语法错误，正确的语法为
增加
kubectl label nodes <node-name> <label-key>=<label-value>  删除
kubectl label nodes <node-name> <label-key>-
修改Label的值
kubectl label nodes <node-name> <label-key>=<label-value> --overwrite
> Update kubernetes.md change label 语法

- docs/php.md
- docs/python.md
- docs/yaml.md
目前PHP、Python、YAML、TOML的“另见”部分有“Learn X in Y minutes”的链接，除了TOML外的三者都有对应的中文版本。
> 将PHP、Python、YAML的“Learn X in Y minutes”链接替换成中文版本

- docs/python.md
- Python 中文文档链接（在 ./docs/python.md 的 “入门” - “介绍” 中）
- Python 类型标注参考清单（在 ./docs/python.md 中）
无
无
> doc: 添加 Python 类型标注

- docs/python.md
在对“错误的类型标注”的说明那一块，示例应当给出一个错误的类型标注，但实际上我写了一个正确的标注。
> 更正 Python 清单类型标注的一处错误

- docs/python.md
- Python 数据模型的清单，也就是 “魔术方法” 那一堆。
工作上查得挺多的，尤其是要找语法糖的对应，所以用了一个表格装起来。
> 添加 Python 数据模型清单

- docs/markdown.md
> fix: markdown.md格式排版问题修复

- docs/swift.md
补全 Switch 分支。
参考代码：https://www.codecademy.com/resources/docs/swift/switch
```
var secondaryColor = "green"
switch secondaryColor {
case "orange":
print("Mix of red and yellow.")
case "green":
print("Mix of blue and yellow.")
case "purple":
print("Mix of red and blue.")
default:
print("This might not be a secondary color.")
}
// Output: Mix of blue and yellow.
```
> Fix Switch statement in swift.md

- docs/python.md
when we installed pipenv pkg, we can't run pipenv install command on our local shell, because maybe we didn't have the site-package-bin dir in system $PATH, so we need to add it firstly.
> [python.md] Add Steps for adding pipenv to system path

- README.md
- docs/glances.md
> feat: Add Glances

- README.md
- docs/vimium.md
又加了一个平时用的浏览器扩展
Vimium 是一个浏览器扩展，主要用于提升在网页浏览器中的导航效率，特别是面向那些习惯使用键盘而不是鼠标的用户。它借鉴了经典文本编辑器 Vim 的键盘快捷键模式，使用户能够在浏览器中高效地进行各种操作，如滚动页面、打开链接、切换标签页等，而不需要依赖鼠标。
> feat: add vimium

- docs/erlang.md
Create an Erlang备忘清单 in markdown format to document common commands and operations for Erlang programming, including入门, 代码结构, 常用内置函数 (BIFs), 并发编程, 错误处理, 分布式编程, OTP框架, 和测试.
This cheat sheet aims to provide a quick reference for Erlang developers and learners, summarizing key points and examples for various aspects of the language.
> feat(docs): add Erlang cheat sheet

- docs/dart.md
当前的异步登录示例代码存在以下问题：
1. `main` 函数中尝试使用 `await userName()`，但 `userName` 是一个字符串变量，而不是一个函数。
2. 应该调用 `login` 函数并使用 `await` 来等待其结果。
`main` 函数应该正确地调用 `login` 函数，并使用 `await` 来等待其结果，然后打印出用户名。
以下是修正后的代码：
```dart
Future<String> login() {
String userName = "Temidjoy";
return Future.delayed(
Duration(seconds: 4), () => userName
);
}
main() async {
print('Authenticating please wait...');
String result = await login();
print(result);
}
> Update dart.md Fix bug in asynchronous login example

- docs/swift.md
新增Swift泛型内容
小修改：
1、新增Range Operators，添加到循环-范围说明里
2、修改Olé为Ole
3、新增数组和集合 默认值初始化方式
4、新增扩展协议示例
> Add Swift Generics

- docs/java.md
> feat: 新增java JDBC

- docs/cpp.md
修正了 C++ 备忘清单中 Lambda 
表达式部分的类型不匹配问题：
- 将混合隐式捕获示例中 func2 的返回类型从 int 改为 string，使其与函数体中实际返回的字符串类型匹配
- 这样可以避免编译错误并提供更准确的示例代码
此外，还修正了以下问题：
- 位运算符部分使用了 HTML 实体来正确显示按位或运算符 (|)
- 变量描述部分将 `char yes = 'Y';` 的注释从"特点"修正为"字符"
这些修改使得 C++ 备忘清单更加准确和可靠，对学习 C++ 的开发者更有帮助。
修改前：
修改后：
> doc: Update cpp.md
